version: "3"

services:
  server:
    #from custom image
    build: ./graphql-server
    image: graphql-server-image
    container_name: graphql-server
    ports:
      - "4000:4000"
  nginx:
    #from custom image
    build: ./angular-graphQL
    image: nginx-image
    container_name: graphql-nginx
    ports:
      - "80:80"
